### ISSUE TITLE
400 Error - The value for one of the HTTP headers is not in the correct format.

### ISSUE THREAD

**Issue by NigelJones55** [ProjectNami/ProjectNamiBlobCache#16]
When using the cache I get the following error:
:  Uncaught WindowsAzure\Common\ServiceException: Fail:
Code: 400
Value: The value for one of the HTTP headers is not in the correct format.
details (if any): ﻿&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;Error&gt;&lt;Code&gt;InvalidHeaderValue&lt;/Code&gt;&lt;Message&gt;The value for one of the HTTP headers is not in the correct format.
RequestId:113b1838-d01c-0061-4d4b-ad1a21000000
Time:2020-10-28T17:00:18.2130249Z&lt;/Message&gt;&lt;HeaderName&gt;x-ms-version&lt;/HeaderName&gt;&lt;HeaderValue&gt;2011-08-18&lt;/HeaderValue&gt;&lt;/Error&gt;. in C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php:382
Stack trace:
#0 C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php(275): WindowsAzure\Common\Internal\Http\HttpClient::throwIfError(400, 'The value for o...', '\xEF\xBB\xBF&lt;?xml versio...', Array)
#1 C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\RestProxy.php(141): WindowsAzure\Commo in 

If I disable the plugin this goes away. Any idea what the problem might be?

**Comment by patrickebates** [comment]
Tell me about your storage account.  What type and version, specifically.

**Comment by NigelJones55** [comment]
Its a StorageV2 (general purpose v2) account on the Premium/Hot tier
![image](https://user-images.githubusercontent.com/73540626/97488774-986b9000-1956-11eb-8e6c-87afad5ecc3a.png)

**Comment by NigelJones55** [comment]
Nothing is being written to the Blob cache.

**Comment by patrickebates** [comment]
You have a container created, and the various parameters have been set in the Application Settings?

**Comment by NigelJones55** [comment]
Yes. I followed the instructions, and the access key etc. is all configured.

**Comment by RolandKamsika** [comment]
I'll try a V1 storage account

**Comment by NigelJones55** [comment]
Tried a V1 storage account and the same error is appearing

**Comment by RolandKamsika** [comment]
:  Uncaught WindowsAzure\Common\ServiceException: Fail:
Code: 400
Value: The value for one of the HTTP headers is not in the correct format.
details (if any): ﻿&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;Error&gt;&lt;Code&gt;InvalidHeaderValue&lt;/Code&gt;&lt;Message&gt;The value for one of the HTTP headers is not in the correct format.
RequestId:d11b0282-301c-001d-2f65-adfc5c000000
Time:2020-10-28T20:05:42.2968221Z&lt;/Message&gt;&lt;HeaderName&gt;x-ms-version&lt;/HeaderName&gt;&lt;HeaderValue&gt;2011-08-18&lt;/HeaderValue&gt;&lt;/Error&gt;. in C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php:382
Stack trace:
#0 C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php(275): WindowsAzure\Common\Internal\Http\HttpClient::throwIfError(400, 'The value for o...', '\xEF\xBB\xBF&lt;?xml versio...', Array)
#1 C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\RestProxy.php(141): WindowsAzure\Commo in

**Comment by NigelJones55** [comment]
:  Uncaught WindowsAzure\Common\ServiceException: Fail:
Code: 400
Value: The value for one of the HTTP headers is not in the correct format.
details (if any): ﻿&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;Error&gt;&lt;Code&gt;InvalidHeaderValue&lt;/Code&gt;&lt;Message&gt;The value for one of the HTTP headers is not in the correct format.
RequestId:d11b0282-301c-001d-2f65-adfc5c000000
Time:2020-10-28T20:05:42.2968221Z&lt;/Message&gt;&lt;HeaderName&gt;x-ms-version&lt;/HeaderName&gt;&lt;HeaderValue&gt;2011-08-18&lt;/HeaderValue&gt;&lt;/Error&gt;. in C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php:382
Stack trace:
#0 C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php(275): WindowsAzure\Common\Internal\Http\HttpClient::throwIfError(400, 'The value for o...', '\xEF\xBB\xBF&lt;?xml versio...', Array)
#1 C:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\RestProxy.php(141): WindowsAzure\Commo in

**Comment by NigelJones55** [comment]
No logs appearing in the site root - but Debug is set to 1

**Comment by patrickebates** [comment]
Looking at the ones I personally have in production.

Storage (general purpose v1)
Standard performance
Secure transfer required = Disabled
Minimum TLS version = 1.0

**Comment by patrickebates** [comment]
The specified version should still be supported
https://docs.microsoft.com/en-us/rest/api/storageservices/previous-azure-storage-service-versions

**Comment by NigelJones55** [comment]
ok I'll give that config a go and let you know.

**Comment by NigelJones55** [comment]
Using that config works. Thanks for the help!
Looking at your code, secure transfer should be supported. Also TLS 1.0 is now deprecated, so I'll take a look at the issues with using both of those. If I make any progress I'll let you know.
Closing this issue.

**Comment by NigelJones55** [comment]
It looks like the Azure PHP libraries in the back end are rather out of
date (2015). I suspect that if you update those it'll solve the problem.
The .NET framework in the front end could also do with updating. I just
built it against framework 4.7.2 and it seems to work ok with the existing
config of the V1 storage account. Without the updated PHP back end I can't
test it with a V2 storage account or the high performance tier, which would
be "nice to have" for enterprise users.
If I can help further let me know.
Thanks again for a great port of Wordpress!

Regards

**Comment by patrickebates** [comment]
what version of PHP are you running on this site that gave you these errors?

**Comment by NigelJones55** [comment]
I used the "Deploy to Azure" button in the ProjectNami GitHub repo, so it's the default Azure Webapp version. According to the MS docs its  version 7.4.5.
https://azure.github.io/AppService/2020/05/04/PHP-Minor-Version-Update-for-July-2020.html
