### ISSUE TITLE
Blob cache and BuddyPress

### ISSUE THREAD

**Issue by EstebanChaves** [ProjectNami/ProjectNamiBlobCache#2]
I`m trying to install buddypress on a multisite network. I have tried network activation and site activation, but once i do it i get the following error:

Fatal error: Uncaught exception 'WindowsAzure\Common\ServiceException' with message 'Fail: Code: 400 Value: The value for one of the HTTP headers is not in the correct format. details (if any): ﻿InvalidHeaderValueThe value for one of the HTTP headers is not in the correct format. RequestId:77df0848-0001-0042-534a-c0bc4e000000 Time:2016-06-06T23:22:11.8696539Zx-ms-version2011-08-18.' in D:\home\site\wwwroot\wp-content\plugins\windows-azure-storage\library\WindowsAzure\Common\Internal\Http\HttpClient.php:382 Stack trace: #0 D:\home\site\wwwroot\wp-content\plugins\windows-azure-storage\library\WindowsAzure\Common\Internal\Http\HttpClient.php(276): WindowsAzure\Common\Internal\Http\HttpClient::throwIfError(400, 'The value for o...', '\xEF\xBB\xBF

**Comment by patrickebates** [comment]
Are you running this on vanilla WordPress or Project Nami?  If on Project Nami, I suspect the problem is BuddyPress and not Blob Cache.  If vanilla WordPress, does the error go away after disabling the Blob Cache plugin and commenting out the Modules declaration in web.config?

**Comment by EstebanChaves** [comment]
Hi Patrick, I'm running on Project Nami. I disabled Blob cache and edited web.confg. After that i enabled buddypress, and  the error is gone. How can  use blob cache with buddypress?

**Comment by patrickebates** [comment]
I'll have to look at that a bit more.  I was under the impression that BuddyPress added a significant amount of DB tables and wouldn't work with PN anyway.

**Comment by EstebanChaves** [comment]
Ok. Thanks. I will apreciate your help!
