### ISSUE TITLE
Seeding Cache for mobile

### ISSUE THREAD

**Issue by awaycott** [ProjectNami/ProjectNamiBlobCache#7]
I see in the code (and observed in practice) that mobile users are cached independently from desktop by adding |mobile to the URL.  However, I don't believe these |mobile users are cached by the seeing webjob.  This means that the first mobile user doesn't ever hit the cache.  

Should the WebJob access each URL twice?

**Comment by patrickebates** [comment]
I guess that adds a bigger question of if the days of needing |mobile are over.  Given the state of responsive sites, maybe bothering with wp_is_mobile to support mobile themes is no longer needed?

**Comment by awaycott** [comment]
I would agree with that.  I am using the Avada theme and from what I can see, the server response (and hence the file to cache) is identical with mobile and desktop users.

**Comment by spencermorin** [comment]
I disagree that it should be removed. :) It's intended to make it so changes to the display based on `wp_is_mobile()` or similar mobile check don't get ignored _or_ served to desktop users. Removing this check, even on a responsive theme, would break that. The need there hasn't changed.

We can, however, add a filter to turn that off so you don't serve two copies of the same thing.

What do you guys think about that?

**Comment by patrickebates** [comment]
So an app setting then, to disable the wp_is_mobile check in both the plugin and the module?

**Comment by awaycott** [comment]
Based on @pippercameron, I would say the safest option would be to change the loader to call each page twice, one with and one without |mobile.  But I suppose you could make an app setting to pick between option, 1, 2 or 3...

**Comment by patrickebates** [comment]
The loader would need to spoof a mobile device in order for the wp_is_mobile checks on theme elements to work correctly, though.

We're going to kick some more ideas around and see if any of them hold up to testing.

**Comment by patrickebates** [comment]
Closing this as moot now that wp_is_mobile is no longer respected by this caching platform
