### ISSUE TITLE
Can project Nami be deployed without Azure?

### ISSUE THREAD

**Issue by rjgoldstein** [ProjectNami/ProjectNamiBlobCache#8]
HI
My Name is Rick Goldstein and my company is DimenXional Cloud Technologies. As you can imagine we are a cloud serivces supplier which is just one of the many serivces we provide as a concirege technology supplier.
So my question is there a version on Nami that does not require an azure account?
If there is please provide the link to the specifics of that flavor of Project Nami.
Thanks

**Comment by patrickebates** [comment]
I note that you made this post on our Blob Cache module.  Are you asking specifically about Blob Cache, or Project Nami itself?

**Comment by rjgoldstein** [comment]
I guess it is the Nami project. For a project I am working on I need a Wordpress website but it need MS SQL express instead of MySQL. I have a piece of software that I need to use for this project that only uses MS Products
		

		Rick Goldstein
From my Cell
rjgoldstein@dimenxional.com
	





On Mon, Jun 12, 2017 at 2:56 PM -0400, "Patrick Bates" <notifications@github.com> wrote:












I note that you made this post on our Blob Cache module.  Are you asking specifically about Blob Cache, or Project Nami itself?

**Comment by patrickebates** [comment]
Yes, it works great on IIS and SQL Server.  We have some Fortune 100 companies using it within their data centers.

https://github.com/ProjectNami/projectnami/releases

http://projectnami.org/download/

**Comment by rjgoldstein** [comment]
Cool you just my next job a lot easier
		

		Rick Goldstein
From my Cell
rjgoldstein@dimenxional.com
	





On Mon, Jun 12, 2017 at 7:22 PM -0400, "Patrick Bates" <notifications@github.com> wrote:












Yes, it works great on IIS and SQL Server.  We have some Fortune 100 companies using it within their data centers.


https://github.com/ProjectNami/projectnami/releases


http://projectnami.org/download/
